
module:
  mounts:
    - source:           img
      target:           assets/hugolib/img
    - source:           partials
      target:           layouts/hugolib/partials
    - source:           shortcodes
      target:           layouts/hugolib/shortcodes